[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd Asset-Manager && npm install"]

[phases.build]
cmds = ["cd Asset-Manager && npm run build"]

[start]
cmd = "cd Asset-Manager && npm run start"
